apiVersion: v1
kind: Pod
metadata:
  name: welocme
  labels:
    namespace: hello-world
spec:
  nodeSelector:
    kubernetes.io/os: linux
  imagePullSecrets:
    - name: ghcr-secret
  containers:
  - image: ghcr.io/arunalk/greetings
    name: greetings
    imagePullPolicy: Always
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 150m
        memory: 200Mi
    ports:
      - containerPort: 8080