apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: welcome-to-hello-world
        image: ghcr.io/arunalk/welcome-to-hello-world:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 150m
            memory: 200Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "90%"
      maxUnavailable: "10%"
