apiVersion: v1
kind: Pod
metadata:
  name: hello-solaria
  labels:
    namespace: hello-world
spec:
  containers:
  - image: docker.io/library/hello-solaria:latest
    name: hello-solaria
    imagePullPolicy: Never
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 150m
        memory: 200Mi
    ports:
      - containerPort: 8080